# Generated by Django 2.2 on 2019-04-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='series',
            name='country',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='series',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='series',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='series',
            name='production',
        ),
        migrations.RemoveField(
            model_name='series',
            name='year',
        ),
    ]
