# Generated by Django 2.1.5 on 2019-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='key',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
