# Generated by Django 2.2 on 2019-05-08 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_vote',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 5, 8, 10, 11, 51, 584325)),
            preserve_default=False,
        ),
    ]
