# Generated by Django 2.1.5 on 2019-02-01 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0002_auto_20190125_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='infos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
