# Generated by Django 2.2 on 2019-04-27 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommandation', '0002_auto_20190420_0850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rating', 'serie', 'user')},
        ),
    ]
