# Generated by Django 2.1.1 on 2019-01-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0002_auto_20181027_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
