# Generated by Django 2.2 on 2019-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0002_rating_date_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_vote',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
