# Generated by Django 2.2 on 2019-05-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0003_auto_20190508_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Les mots cités dans les series', 'verbose_name_plural': 'Les mots cités dans les series'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Les votes', 'verbose_name_plural': 'Les votes'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Les series', 'verbose_name_plural': 'Les series'},
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serie', to='recommandation.Series')),
                ('similar_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='similar_to', to='recommandation.Series')),
            ],
        ),
    ]
