# Generated by Django 2.2 on 2019-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0004_auto_20190508_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Similarity',
        ),
    ]
