# Generated by Django 2.2 on 2019-05-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0005_delete_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serie', to='recommandation.Series')),
                ('similar_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='similar_to', to='recommandation.Series')),
            ],
        ),
    ]
