# Generated by Django 2.2 on 2019-05-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0006_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.CharField(max_length=35, null=True, unique=True)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
    ]
