# Generated by Django 2.2 on 2019-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0007_searchcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_local',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='searchcount',
            name='count',
            field=models.IntegerField(),
        ),
    ]
