# Generated by Django 2.2 on 2019-05-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0008_auto_20190512_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Mot', 'verbose_name_plural': 'Les mots des sous titres'},
        ),
        migrations.AlterModelOptions(
            name='posting',
            options={'verbose_name': 'Le mot de la serie', 'verbose_name_plural': 'Les mots des series'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Le vote', 'verbose_name_plural': 'Les votes'},
        ),
        migrations.AlterModelOptions(
            name='searchcount',
            options={'verbose_name': 'Recherche', 'verbose_name_plural': 'Les recherches'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Une series', 'verbose_name_plural': 'Les series'},
        ),
    ]
