# Generated by Django 2.2 on 2019-05-25 16:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0009_auto_20190525_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'verbose_name': 'Mot cité dans une serie', 'verbose_name_plural': 'Corpus des series'},
        ),
        migrations.AlterField(
            model_name='keywords',
            name='idf',
            field=models.FloatField(null=True, verbose_name='Inverse document Frequency'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='key',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Mot'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='series',
            field=models.ManyToManyField(through='recommandation.Posting', to='recommandation.Series', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommandation.KeyWords', verbose_name='Mot'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='number',
            field=models.IntegerField(verbose_name='Nombre de fois que le mot est cité'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommandation.Series', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='tf',
            field=models.FloatField(null=True, verbose_name='Term Frequency'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_vote',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de vote'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', "J'aime"), ('0', "Je n'aime pas")], max_length=1, verbose_name='Notation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='searchcount',
            name='count',
            field=models.IntegerField(verbose_name='Nombre de recherche'),
        ),
        migrations.AlterField(
            model_name='searchcount',
            name='search_key',
            field=models.CharField(max_length=35, null=True, unique=True, verbose_name='Mot de recherche'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='series',
            name='infos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Informations complémentaires'),
        ),
        migrations.AlterField(
            model_name='series',
            name='max_keyword_nb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max du mot le plus cité'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nom du dossier'),
        ),
        migrations.AlterField(
            model_name='series',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la serie'),
        ),
    ]
