# Generated by Django 2.2 on 2019-06-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0010_auto_20190525_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Une serie', 'verbose_name_plural': 'Les series'},
        ),
        migrations.AlterModelOptions(
            name='similarity',
            options={'verbose_name': 'Similaire', 'verbose_name_plural': 'Similarités'},
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='series',
        ),
        migrations.AlterField(
            model_name='posting',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.KeyWords', verbose_name='Mot'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommandation.Series', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='recommandation.Series'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='similar_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='recommandation.Series'),
        ),
    ]
